Repository hoangr1010/Cupid, pull requests merged in 2024-05, with the labels that each got.

#100 Unit test server
  client/src/api/user.js
  server/controllers/Opening.js
  server/controllers/Request.js
  server/controllers/User.js
  server/middleware/User.js
  server/models/Request.js
  server/routes/Opening.js
  server/routes/Request.js
  server/routes/User.js
  server/test/Opening/createOpening.js
  server/test/Opening/getAllOpening.js
  server/test/Opening/getOneOpening.js
  server/test/Opening/index.js
  server/test/Request/createRequest.js
  server/test/Request/getAllRequest.js
  server/test/Request/getOneRequest.js
  server/test/Request/index.js
  server/test/User/index.js
  server/test/User/updateResume.js
  server/test/index.test.js
Labels: backend, testing

#97 Matching algorithm (first-come-first-serve) based on scale
  matching-algorithm/.gitignore
  matching-algorithm/models/Opening.js
  matching-algorithm/models/Request.js
  matching-algorithm/models/User.js
  matching-algorithm/package-lock.json
  matching-algorithm/package.json
  matching-algorithm/script/index.js
  matching-algorithm/utils/connectDB.js
  matching-algorithm/utils/date.js
  server/seeds/sampleData.js
Labels: backend

#111 add event and function to serverless.yml
  server/handler.js
  server/matching-algorithm/index.js
  server/serverless.yml
Labels: backend

#110 FInished creating table view for request
  client/package-lock.json
  client/package.json
  client/src/pages/RequestDashboardPage/RequestCard.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  server/package-lock.json
  server/package.json
Labels: frontend

#115 Polish request UI
  client/src/api/request.js
  client/src/components/CompanyDropDown/index.jsx
  client/src/pages/ProfilePage/index.jsx
  client/src/pages/RequestDashboardPage/CreateRequest.jsx
  client/src/pages/RequestDashboardPage/CreateRequestModal.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  client/src/utils/request.js
  server/src/controllers/Request.js
  server/src/routes/Request.js
Labels: frontend, backend

#119 Referred status
  client/src/components/StatusBadge/index.jsx
  client/src/index.css
  client/src/pages/OpeningDashboardPage/OpeningDashboard.jsx
  client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
  client/src/pages/OpeningDashboardPage/OpeningView.jsx
  matching-algorithm/.gitignore
  matching-algorithm/models/Opening.js
  matching-algorithm/models/Request.js
  matching-algorithm/models/User.js
  matching-algorithm/package-lock.json
  matching-algorithm/package.json
  matching-algorithm/script/index.js
  matching-algorithm/utils/connectDB.js
  matching-algorithm/utils/date.js
Labels: frontend

#132 add job posting on create request
  client/src/api/request.js
  client/src/pages/RequestDashboardPage/CreateRequest.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  server/src/models/Request.js
Labels: frontend, backend

#128 calculate scale for each request
  server/matching-algorithm/index.js
  server/matching-algorithm/scale/scale.js
  server/seeds/sampleData.js
Labels: backend

#133 jwt authentication
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/api/auth.js
  client/src/state/index.js
  client/src/utils/api.js
  server/package-lock.json
  server/package.json
  server/src/controllers/Auth.js
  server/src/middleware/Auth.js
  server/src/routes/Opening.js
  server/src/routes/Request.js
  server/src/routes/User.js
Labels: backend

#134 upload resume to s3
  .vscode/settings.json
  client/src/api/user.js
  client/src/pages/ProfilePage/index.jsx
  server/package-lock.json
  server/package.json
  server/src/controllers/User.js
  server/src/middleware/resumeUpload.js
  server/src/routes/User.js
Labels: frontend, backend

#146 Polish sidebar opening
  .github/workflows/server-deploy.yml
  client/public/index.html
  client/src/api/opening.js
  client/src/components/Sidebar/SidebarItem.jsx
  client/src/components/StatusBadge/index.jsx
  client/src/index.css
  client/src/pages/OpeningDashboardPage/OpeningDashboard.jsx
  client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
  client/src/pages/OpeningDashboardPage/OpeningView.jsx
  client/src/tailwind.js
  server/src/controllers/Opening.js
Labels: frontend

#150 polish homepage
  client/src/index.css
  client/src/pages/HomePage/CompanyCard.jsx
  client/src/pages/HomePage/StatisticsTable.jsx
  client/src/pages/HomePage/index.jsx
  client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  client/src/tailwind.js
Labels: frontend
