Repository hoangr1010/Cupid, pull requests merged in 2024-04, with the labels that each got.

#21 Direct user to proper page after logging in
  client/src/App.jsx
  client/src/pages/LandingPage/Redirect.jsx
  client/src/pages/OnboardPage/ExperienceForm.jsx
  client/src/pages/ProfilePage/ProfilePage.jsx
  client/src/state/index.js
Labels: frontend

#28 Implement CREATE + GET api for request
  server/controllers/RequestController.js
  server/index.js
  server/routes/RequestRouter.js
Labels: backend

#32 Implement GET api for all requests within 3 months
  server/controllers/RequestController.js
  server/controllers/date-utilities.js
  server/models/Request.js
  server/routes/RequestRouter.js
Labels: backend

#37 create PR template
  .github/pull_request_template.md
Labels: config

#34 Setup prettier
  .prettierignore
  .prettierrc.json
  .vscode/settings.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/Sidebar.jsx
  client/src/components/SidebarItem.jsx
  client/src/components/icons/LoadingIcon.jsx
  client/src/index.css
  client/src/index.js
  client/src/pages/LandingPage/Redirect.jsx
  client/src/pages/LandingPage/index.jsx
  client/src/pages/OnboardPage/Education.jsx
  client/src/pages/OnboardPage/Experience.jsx
  client/src/pages/OnboardPage/ExperienceForm.jsx
  client/src/pages/OnboardPage/index.jsx
  client/src/pages/OpeningDashboardPage/OpeningDashboardPage.jsx
  client/src/pages/ProfilePage/ProfilePage.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  client/src/pages/RequestDashboardPage/index.jsx
  client/src/state/index.js
  client/tailwind.config.js
  server/controllers/AuthController.js
  server/controllers/RequestController.js
  server/controllers/UserController.js
  server/controllers/date-utilities.js
  server/index.js
  server/models/Request.js
  server/models/User.js
  server/routes/AuthRouter.js
  server/routes/RequestRouter.js
  server/routes/UserRouter.js
Labels: config

#33 Make UI for request dashboard + request creation form
  client/src/App.jsx
  client/src/components/Sidebar.jsx
  client/src/pages/RequestCreatePage/Form.jsx
  client/src/pages/RequestCreatePage/index.jsx
  client/src/pages/RequestDashboardPage/RequestCard.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  client/src/pages/RequestDashboardPage/index.jsx
Labels: frontend

#46 Set up axios & refactor component actions
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/api/auth.js
  client/src/api/index.js
  client/src/pages/LandingPage/Redirect.jsx
  client/src/pages/RequestCreatePage/Form.jsx
  client/src/pages/RequestCreatePage/index.jsx
  client/src/pages/RequestDashboardPage/RequestCard.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  client/src/utils/api.js
  server/controllers/AuthController.js
Labels: frontend

#50 set up redux persist
  client/src/index.js
Labels: frontend

#53 add protected route
  client/src/App.jsx
  client/src/components/ProtectedRoute/index.jsx
  client/src/components/icons/LoadingIcon.jsx
  client/src/pages/LandingPage/Redirect.jsx
Labels: frontend

#52 install & implement sonner
  client/package-lock.json
  client/package.json
  client/src/index.js
Labels: frontend

#56 upgrade sidebar UI
  client/public/index.html
  client/src/App.jsx
  client/src/components/ProtectedRoute/index.jsx
  client/src/components/Sidebar.jsx
  client/src/components/Sidebar/RouteContainer.jsx
  client/src/components/Sidebar/SidebarItem.jsx
  client/src/components/Sidebar/index.jsx
  client/src/components/SidebarItem.jsx
  client/src/index.css
  client/src/index.js
  client/src/pages/LandingPage/Redirect.jsx
  client/src/pages/OpeningDashboardPage/OpeningDashboardPage.jsx
  client/src/pages/ProfilePage/ProfilePage.jsx
  client/src/pages/RequestDashboardPage/index.jsx
  client/tailwind.config.js
Labels: frontend

#30 CR endpoints for OPENING
  server/controllers/OpeningController.js
  server/index.js
  server/models/Opening.js
  server/routes/OpeningRouter.js
Labels: frontend

#58 add bottombar in sidebar
  client/src/components/Sidebar/BottomBar.jsx
  client/src/components/Sidebar/SidebarItem.jsx
  client/src/components/Sidebar/index.jsx
  client/src/state/index.js
  client/src/utils/auth.js
  server/controllers/AuthController.js
Labels: frontend

#54 Sample data
  server/data/sampleData.js
  server/data/script.js
  server/package-lock.json
  server/package.json
Labels: backend

#64 update yml file
  .github/workflows/main.yml
Labels: testing

#68 change User model, update picture_url functionality
  client/src/api/auth.js
  client/src/components/Sidebar/BottomBar.jsx
  client/src/state/index.js
  server/controllers/Auth.js
  server/models/User.js
Labels: bug, frontend

#76 Polish Opening page and Popup create
  client/src/App.jsx
  client/src/api/opening.js
  client/src/api/request.js
  client/src/components/Sidebar/BottomBar.jsx
  client/src/pages/LandingPage/Redirect.jsx
  client/src/pages/OpeningDashboardPage/AddSlotButton.jsx
  client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx
  client/src/pages/OpeningDashboardPage/CreateOpeningPage.jsx
  client/src/pages/OpeningDashboardPage/GetAllOpenings.jsx
  client/src/pages/OpeningDashboardPage/OpeningDashboard.jsx
  client/src/pages/OpeningDashboardPage/OpeningSlotCard.jsx
  client/src/state/index.js
Labels: frontend

#69 add protected logic for route Redirect
  client/src/App.jsx
  client/src/api/auth.js
  client/src/pages/LandingPage/Redirect.jsx
Labels: bug, frontend

#73 Make CreateRequestPage functional with backend
  client/src/App.jsx
  client/src/api/request.js
  client/src/pages/RequestCreatePage/Form.jsx
  client/src/pages/RequestCreatePage/index.jsx
  client/src/pages/RequestDashboardPage/CreateRequestPage.jsx
  client/src/pages/RequestDashboardPage/index.jsx
Labels: frontend

#89 fix bug onboard navigation
  client/src/pages/LandingPage/Redirect.jsx
Labels: bug, frontend

#91 rewrite sample data and modify script based on userid
  client/src/pages/OpeningDashboardPage/OpeningSlotCard.jsx
  server/data/sampleData.js
  server/data/script.js
  server/package.json
  server/seeds/index.js
  server/seeds/sampleData.js
Labels: backend
