Repository hoangr1010/Cupid, pull requests merged in 2024-06, with the labels that each got.

#160 Optimize api
  server/src/controllers/Opening.js
  server/src/controllers/Request.js
  server/src/middleware/User.js
  server/src/routes/Company.js
  server/src/routes/Opening.js
  server/src/routes/Request.js
  server/src/services/s3.js
Labels: backend

#172 Automatically get recipientId when creating a Notification
  notification-service/microservice/Notification.js
  notification-service/routes/Notification.js
  server/src/routes/User.js
  server/src/utils/notification.js
Labels: backend

#174 Optimize opening
  client/package-lock.json
  client/package.json
  client/src/api/opening.js
  client/src/components/EvaluationText/index.jsx
  client/src/components/PercentageChart/index.jsx
  client/src/components/StatusBadge/index.jsx
  client/src/index.css
  client/src/pages/HomePage/StatisticsTable.jsx
  client/src/pages/OpeningDashboardPage/CandidateView.jsx
  client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx
  client/src/pages/OpeningDashboardPage/OpeningDashboard.jsx
  client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
  client/src/pages/OpeningDashboardPage/OpeningView.jsx
  client/src/pages/OpeningDashboardPage/OverviewView.jsx
  client/src/pages/OpeningDashboardPage/TableView.jsx
  client/src/pages/ProfilePage/index.jsx
  client/src/pages/RequestDashboardPage/RequestDashboard.jsx
  client/src/state/index.js
  client/src/tailwind.js
  client/src/utils/theme.js
  notification-service/utils/connectDB.js
  server/index.js
  server/matching-algorithm/index.js
  server/seeds/index.js
  server/seeds/sampleData.js
  server/src/controllers/Opening.js
  server/src/controllers/Request.js
  server/src/models/Opening.js
  server/src/models/Passcode.js
  server/src/models/Request.js
  server/src/routes/Opening.js
  server/src/routes/Request.js
  server/test/MatchingAlgorithm/runMatchingAlgorithm.js
Labels: frontend, backend, perf

#187 Request info opening
  client/src/App.jsx
  client/src/api/opening.js
  client/src/components/ConversationBox/Message.jsx
  client/src/components/ConversationBox/index.jsx
  client/src/components/Notification/index.jsx
  client/src/components/Sidebar/index.jsx
  client/src/index.css
  client/src/pages/OpeningDashboardPage/CandidateView/index.jsx
  client/src/pages/OpeningDashboardPage/OpeningDashboard.jsx
  client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
  client/src/pages/OpeningDashboardPage/OpeningInfoModal/index.jsx
  client/src/pages/OpeningDashboardPage/RequestInfoModal.jsx
  client/src/pages/OpeningDashboardPage/StartingView/CreateOpeningModal.jsx
  client/src/pages/OpeningDashboardPage/TableView/QuickAction.jsx
  client/src/pages/OpeningDashboardPage/TableView/index.jsx
  client/src/state/index.js
  server/src/controllers/Request.js
  server/src/models/Request.js
  server/src/routes/Request.js
Labels: frontend, backend
